/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Bavaresco
 */
public class Calculadora extends javax.swing.JFrame {

    /**
     * Creates new form Calculadora
     */
    public Calculadora() {
        initComponents();
    }
Double valor1,valor2;
String sinal;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        textArea = new javax.swing.JTextField();
        umBtn = new javax.swing.JButton();
        quatroBtn = new javax.swing.JButton();
        seteBtn = new javax.swing.JButton();
        igualBtn = new javax.swing.JButton();
        menosBtn = new javax.swing.JButton();
        doisBtn = new javax.swing.JButton();
        tresBtn = new javax.swing.JButton();
        cincoBtn = new javax.swing.JButton();
        seisBtn = new javax.swing.JButton();
        oitoBtn = new javax.swing.JButton();
        noveBtn = new javax.swing.JButton();
        maisBtn = new javax.swing.JButton();
        vezesBtn = new javax.swing.JButton();
        barraBtn = new javax.swing.JButton();
        zeroBtn = new javax.swing.JButton();
        pontoBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(0, 51, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("        CALCULADORA");

        textArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textAreaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(145, Short.MAX_VALUE))
            .addComponent(textArea, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(textArea, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        umBtn.setBackground(new java.awt.Color(255, 255, 255));
        umBtn.setForeground(new java.awt.Color(0, 51, 255));
        umBtn.setText("1");
        umBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                umBtnActionPerformed(evt);
            }
        });

        quatroBtn.setBackground(new java.awt.Color(255, 255, 255));
        quatroBtn.setForeground(new java.awt.Color(0, 51, 255));
        quatroBtn.setText("4");
        quatroBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quatroBtnActionPerformed(evt);
            }
        });

        seteBtn.setBackground(new java.awt.Color(255, 255, 255));
        seteBtn.setForeground(new java.awt.Color(0, 51, 255));
        seteBtn.setText("7");
        seteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seteBtnActionPerformed(evt);
            }
        });

        igualBtn.setBackground(new java.awt.Color(255, 255, 255));
        igualBtn.setForeground(new java.awt.Color(0, 51, 255));
        igualBtn.setText("=");
        igualBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                igualBtnActionPerformed(evt);
            }
        });

        menosBtn.setBackground(new java.awt.Color(255, 255, 255));
        menosBtn.setForeground(new java.awt.Color(0, 51, 255));
        menosBtn.setText("-");
        menosBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menosBtnActionPerformed(evt);
            }
        });

        doisBtn.setBackground(new java.awt.Color(255, 255, 255));
        doisBtn.setForeground(new java.awt.Color(0, 51, 255));
        doisBtn.setText("2");
        doisBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doisBtnActionPerformed(evt);
            }
        });

        tresBtn.setBackground(new java.awt.Color(255, 255, 255));
        tresBtn.setForeground(new java.awt.Color(0, 51, 255));
        tresBtn.setText("3");
        tresBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tresBtnActionPerformed(evt);
            }
        });

        cincoBtn.setBackground(new java.awt.Color(255, 255, 255));
        cincoBtn.setForeground(new java.awt.Color(0, 51, 255));
        cincoBtn.setText("5");
        cincoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cincoBtnActionPerformed(evt);
            }
        });

        seisBtn.setBackground(new java.awt.Color(255, 255, 255));
        seisBtn.setForeground(new java.awt.Color(0, 51, 255));
        seisBtn.setText("6");
        seisBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seisBtnActionPerformed(evt);
            }
        });

        oitoBtn.setBackground(new java.awt.Color(255, 255, 255));
        oitoBtn.setForeground(new java.awt.Color(0, 51, 255));
        oitoBtn.setText("8");
        oitoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oitoBtnActionPerformed(evt);
            }
        });

        noveBtn.setBackground(new java.awt.Color(255, 255, 255));
        noveBtn.setForeground(new java.awt.Color(0, 51, 255));
        noveBtn.setText("9");
        noveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noveBtnActionPerformed(evt);
            }
        });

        maisBtn.setBackground(new java.awt.Color(255, 255, 255));
        maisBtn.setForeground(new java.awt.Color(0, 51, 255));
        maisBtn.setText("+");
        maisBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maisBtnActionPerformed(evt);
            }
        });

        vezesBtn.setBackground(new java.awt.Color(255, 255, 255));
        vezesBtn.setForeground(new java.awt.Color(0, 51, 255));
        vezesBtn.setText("*");
        vezesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vezesBtnActionPerformed(evt);
            }
        });

        barraBtn.setBackground(new java.awt.Color(255, 255, 255));
        barraBtn.setForeground(new java.awt.Color(0, 51, 255));
        barraBtn.setText("/");
        barraBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barraBtnActionPerformed(evt);
            }
        });

        zeroBtn.setBackground(new java.awt.Color(255, 255, 255));
        zeroBtn.setForeground(new java.awt.Color(0, 51, 255));
        zeroBtn.setText("0");
        zeroBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zeroBtnActionPerformed(evt);
            }
        });

        pontoBtn.setForeground(new java.awt.Color(0, 51, 204));
        pontoBtn.setText(".");
        pontoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pontoBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(zeroBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(seteBtn)
                            .addComponent(quatroBtn)
                            .addComponent(umBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(doisBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(oitoBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cincoBtn, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addComponent(barraBtn))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(tresBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(vezesBtn)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(noveBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(seisBtn)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(maisBtn)
                    .addComponent(menosBtn)
                    .addComponent(igualBtn)
                    .addComponent(pontoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(barraBtn)
                    .addComponent(vezesBtn)
                    .addComponent(menosBtn))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seteBtn)
                    .addComponent(oitoBtn)
                    .addComponent(noveBtn)
                    .addComponent(maisBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quatroBtn)
                    .addComponent(cincoBtn)
                    .addComponent(seisBtn)
                    .addComponent(igualBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(umBtn)
                    .addComponent(doisBtn)
                    .addComponent(tresBtn)
                    .addComponent(pontoBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(zeroBtn)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textAreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textAreaActionPerformed

    private void zeroBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zeroBtnActionPerformed
        // TODO add your handling code here:
        textArea.setText(textArea.getText()+"0");
    }//GEN-LAST:event_zeroBtnActionPerformed

    private void umBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_umBtnActionPerformed
        // TODO add your handling code here:
        textArea.setText(textArea.getText()+"1");
    }//GEN-LAST:event_umBtnActionPerformed

    private void doisBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doisBtnActionPerformed
        // TODO add your handling code here:
        textArea.setText(textArea.getText()+"2");
    }//GEN-LAST:event_doisBtnActionPerformed

    private void tresBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tresBtnActionPerformed
        // TODO add your handling code here:
        textArea.setText(textArea.getText()+"3");
    }//GEN-LAST:event_tresBtnActionPerformed

    private void quatroBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quatroBtnActionPerformed
        // TODO add your handling code here:
        textArea.setText(textArea.getText()+"4");
    }//GEN-LAST:event_quatroBtnActionPerformed

    private void cincoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cincoBtnActionPerformed
        // TODO add your handling code here:
        textArea.setText(textArea.getText()+"5");
    }//GEN-LAST:event_cincoBtnActionPerformed

    private void seisBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seisBtnActionPerformed
        // TODO add your handling code here:
        textArea.setText(textArea.getText()+"6");
    }//GEN-LAST:event_seisBtnActionPerformed

    private void seteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seteBtnActionPerformed
        // TODO add your handling code here:
        textArea.setText(textArea.getText()+"7");
    }//GEN-LAST:event_seteBtnActionPerformed

    private void oitoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oitoBtnActionPerformed
        // TODO add your handling code here:
        textArea.setText(textArea.getText()+"8");
    }//GEN-LAST:event_oitoBtnActionPerformed

    private void noveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noveBtnActionPerformed
        // TODO add your handling code here:
        textArea.setText(textArea.getText()+"9");
    }//GEN-LAST:event_noveBtnActionPerformed

    private void igualBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_igualBtnActionPerformed
        // TODO add your handling code here:
        valor2=Double.parseDouble(textArea.getText());
        if(sinal=="soma")
        {
            textArea.setText(String.valueOf(valor1+valor2));
        }else if(sinal=="menos")
        {
             textArea.setText(String.valueOf(valor1-valor2));
        }
        else if(sinal=="vezes")
        {
             textArea.setText(String.valueOf(valor1*valor2));
        }
        else if(sinal=="dividir")
        {
             textArea.setText(String.valueOf(valor1/valor2));
        }
    }//GEN-LAST:event_igualBtnActionPerformed

    private void maisBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maisBtnActionPerformed
        // TODO add your handling code here:
        
        valor1=Double.parseDouble(textArea.getText());
        textArea.setText("");
        sinal="soma";
    }//GEN-LAST:event_maisBtnActionPerformed

    private void menosBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menosBtnActionPerformed
        // TODO add your handling code here:
        valor1=Double.parseDouble(textArea.getText());
        textArea.setText("");
        sinal="menos";
    }//GEN-LAST:event_menosBtnActionPerformed

    private void vezesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vezesBtnActionPerformed
        // TODO add your handling code here:
        valor1=Double.parseDouble(textArea.getText());
        textArea.setText("");
        sinal="vezes";
    }//GEN-LAST:event_vezesBtnActionPerformed

    private void barraBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barraBtnActionPerformed
        // TODO add your handling code here:
        valor1=Double.parseDouble(textArea.getText());
        textArea.setText("");
        sinal="dividir";
    }//GEN-LAST:event_barraBtnActionPerformed

    private void pontoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pontoBtnActionPerformed
        // TODO add your handling code here:
        textArea.setText(textArea.getText()+".");
    }//GEN-LAST:event_pontoBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton barraBtn;
    private javax.swing.JButton cincoBtn;
    private javax.swing.JButton doisBtn;
    private javax.swing.JButton igualBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton maisBtn;
    private javax.swing.JButton menosBtn;
    private javax.swing.JButton noveBtn;
    private javax.swing.JButton oitoBtn;
    private javax.swing.JButton pontoBtn;
    private javax.swing.JButton quatroBtn;
    private javax.swing.JButton seisBtn;
    private javax.swing.JButton seteBtn;
    private javax.swing.JTextField textArea;
    private javax.swing.JButton tresBtn;
    private javax.swing.JButton umBtn;
    private javax.swing.JButton vezesBtn;
    private javax.swing.JButton zeroBtn;
    // End of variables declaration//GEN-END:variables
}
