var mundo = 'mundo';
 const nome = 'Mauricio';
 const sobrenome= '';
 const nomecompleto=nome+sobrenome;
 console.log(nomecompleto);
console.log(`Ola  ${mundo}  `+mundo);
let radius = 4;
let area = Math.PI*radius*radius;
console.log(`The radius of circle is ${radius}.`);
console.log(`The area of circle is ${area}.`);
const listaDeDestinos = new Array(`Salvador`,`Rio de janeiro`,`São paulo`);
listaDeDestinos.push('Ola mundo');
listaDeDestinos.push('Caxias do sul');
console.log(listaDeDestinos);
console.log(listaDeDestinos[0]);
 listaDeDestinos.splice(0,1);
 
console.log(listaDeDestinos);
console.log(listaDeDestinos[0]);
console.log(5**22);
const idadePessoaUm =215;
const idadePessoaDois = 26;
console.log(Math.max(idadePessoaUm,idadePessoaDois));
const teste = true;
const testeDois=false;
console.log(testeDois);
console.log(teste);
const auxiliar = teste == true || testeDois==true;
console.log(auxiliar);