/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import classes.Atrativo;
import classes.Categoria;
import classes.Servico;
import classes.Usuario;
import persistencias.PersistenciaSerializada;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author USER_IURI
 */
public class CadastroServico extends javax.swing.JFrame {

    private ArrayList<Servico> listaServicos;
    private ArrayList<Categoria> listaCategorias;
    private ArrayList<Atrativo> listaAtrativos;
    
    private Usuario usu;
    private Servico ser;
    private Atrativo atra;
    private Categoria cat;
    private int opcao;
    
    
    private PersistenciaSerializada ps = new PersistenciaSerializada();
    /**
     * Creates new form Cadastro_Serviço
     */
    public CadastroServico(ArrayList<Servico> listaServicos,ArrayList<Categoria> listaCategorias,ArrayList<Atrativo> listaAtrativos) {
        this.listaServicos = listaServicos;
        this.listaCategorias = listaCategorias;
        this.listaAtrativos = listaAtrativos;       
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField4 = new javax.swing.JTextField();
        nomeT = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nomeatrativoT = new javax.swing.JTextField();
        cadastrar = new javax.swing.JButton();
        enderecoT = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        precotxtT = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        categoriaT = new javax.swing.JTextField();
        cidadeT = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        jTextField4.setText("jTextField4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Serviço");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(500, 500));
        setResizable(false);

        nomeT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeTActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Nome do Serviço:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Endereço:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Preço R$:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Atrativo:");

        cadastrar.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        cadastrar.setText("Cadastrar");
        cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI Symbol", 1, 24)); // NOI18N
        jLabel5.setText("Cadastro de Serviço");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rubisco.jpg"))); // NOI18N

        precotxtT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precotxtTActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Cidade:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Categoria:");

        cidadeT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cidadeTActionPerformed(evt);
            }
        });

        jButton1.setText("< Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel8))
                                .addGap(28, 28, 28))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(26, 26, 26)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(nomeatrativoT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(precotxtT, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cidadeT, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(enderecoT, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomeT, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(categoriaT))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel5)
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(enderecoT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cidadeT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(precotxtT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(nomeatrativoT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(categoriaT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nomeTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeTActionPerformed

    private void cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarActionPerformed
       
        //deserializa
 /*       try {
            listaServicos = (ArrayList<Servico>) ps.deserializarListServico("ListServico");            
        } 
        catch (Exception ex) {
            System.err.println("Falha ao deserializar! - " + ex.toString());
        }*/
           
        float preco = 0;
        try{
          preco = Float.parseFloat(precotxtT.getText());
       }
       catch(NumberFormatException a){
           JOptionPane.showMessageDialog(null,"O Preço não deve possuir letras, vírgulas, ou caracteres especiais!"); 
       }
        if(nomeT.getText().equals("")){ 
           JOptionPane.showMessageDialog(null,"Nome Obrigatorio!");
       }
        else if(enderecoT.getText().equals("")){ 
           JOptionPane.showMessageDialog(null,"Endereço Obrigatorio!");
       }
        else if(cidadeT.getText().equals("")){ 
           JOptionPane.showMessageDialog(null,"Cidade Obrigatoria!");
       }
        else if(preco == 0){ 
           JOptionPane.showMessageDialog(null,"Preço Obrigatorio!");
       }
        else if(nomeatrativoT.getText().equals("")){ 
           JOptionPane.showMessageDialog(null,"Atrativo Obrigatorio!");
       }
        else if(categoriaT.getText().equals("")){ 
           JOptionPane.showMessageDialog(null,"Categoria Obrigatoria!");
       }
        else { // se todas as variaveis são validas, inclui e fecha a janela
 
                    // verifica se atrativo ja existe na lista
                    // se ja existe, passa a referencia para o objeto servico
                    int flag=0;
                    for(int i=0; i<listaAtrativos.size(); i++){                       
                        if (nomeatrativoT.getText().equals(listaAtrativos.get(i).getNome())){
                            ser = new Servico(nomeT.getText(),enderecoT.getText(),cidadeT.getText(),preco,listaAtrativos.get(i));  
                            listaAtrativos.get(i).incluirServico(ser);
                            flag=1;
                            break;
                        }
                    }
                    // caso o atrativo nao exista na lista
                    // cria novo atrativo, adiciona na lista, e passa a referencia
                    // para o objeto servico
                    if (flag==0){
                        atra = new Atrativo(nomeatrativoT.getText(),cidadeT.getText());
                        listaAtrativos.add(atra);
                        ser = new Servico(nomeT.getText(),enderecoT.getText(),cidadeT.getText(),preco,atra);
                        atra.incluirServico(ser);
                    }
                    
                    // verifica se categoria já existe na lista
                    // se ja existe, seta a categoria no objeto servico
                    flag=0;
                    for(int i=0; i<listaCategorias.size(); i++){
                        if (listaCategorias.get(i).getNome().equals(categoriaT.getText())){
                            ser.setCat(listaCategorias.get(i));  
                            listaCategorias.get(i).incluirServico(ser);
                            flag=1;
                            break;
                        }
                    }
                    // caso a categoria nao exista na lista
                    // cria nova categoria, adiciona na lista, e seta 
                    // a categoria no objeto servico
                    if (flag==0){
                        cat = new Categoria(categoriaT.getText());
                        ser.setCat(cat);
                        cat.incluirServico(ser);
                        listaCategorias.add(cat);
                    }                                 
                    
                    // adiciona o novo servico na lista
                    listaServicos.add(ser);//adicionando no fim da lista por enquanto  
                    
                    
                     for(int i=0; i<listaServicos.size(); i++){//Estou printando para ter certeza que esta adicionando
                        System.out.println( listaServicos.get(i).toString());
                    }
                     
                     
            this.setVisible(false);
        }
        
        
      
    }//GEN-LAST:event_cadastrarActionPerformed

    private void precotxtTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precotxtTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precotxtTActionPerformed

    private void cidadeTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cidadeTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cidadeTActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new CadastroServico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastrar;
    private javax.swing.JTextField categoriaT;
    private javax.swing.JTextField cidadeT;
    private javax.swing.JTextField enderecoT;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField nomeT;
    private javax.swing.JTextField nomeatrativoT;
    private javax.swing.JTextField precotxtT;
    // End of variables declaration//GEN-END:variables
}
