/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import classes.*;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.util.ArrayList;
import java.util.Scanner;
import javax.swing.JFrame;

import javax.swing.JOptionPane;
import persistencias.PersistenciaSerializada;

/**
 *
 * @author Samsung
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    private ArrayList<Usuario> listaUsuario = new ArrayList();
    private ArrayList<Usuario> listaProvedor = new ArrayList();
    private ArrayList<Servico> listaServicos = new ArrayList();
    private ArrayList<Atrativo> listaAtrativos = new ArrayList();
    private ArrayList<Categoria> listaCategorias = new ArrayList();
    private PersistenciaSerializada ps = new PersistenciaSerializada();
    private Usuario usu;
    private Servico ser;
    private Atrativo atra;
    private Categoria cat;
    private int opcao;
    private Scanner ler = new Scanner(System.in);
    private Controle controle = new Controle(); // classe que possui as avariaveis de controle

    public Menu() {
        initComponents();
        recuperaSerializado();
        this.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/images/rubisco.jpg")).getImage());
        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        this.addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent ev) {
                salvaSerializado();
                System.exit(0);
            }

        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel3 = new javax.swing.JLabel();
        restCheckBox = new javax.swing.JCheckBox();
        hotCheckBox = new javax.swing.JCheckBox();
        barCheckBox = new javax.swing.JCheckBox();
        cafeCheckBox = new javax.swing.JCheckBox();
        evCheckBox = new javax.swing.JCheckBox();
        cultCheckBox = new javax.swing.JCheckBox();
        outrosCheckBox = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        cidadelabel = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        orcamentolabel = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        solicitar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mLogin = new javax.swing.JMenuItem();
        mLogin1 = new javax.swing.JMenuItem();
        mSair = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu22 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RUBISCO TEAM");

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel3.setText("Categorias:");

        restCheckBox.setBackground(new java.awt.Color(255, 255, 255));
        restCheckBox.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        restCheckBox.setText("Restaurantes");
        restCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restCheckBoxActionPerformed(evt);
            }
        });

        hotCheckBox.setBackground(new java.awt.Color(255, 255, 255));
        hotCheckBox.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        hotCheckBox.setText("Hotéis");
        hotCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hotCheckBoxActionPerformed(evt);
            }
        });

        barCheckBox.setBackground(new java.awt.Color(255, 255, 255));
        barCheckBox.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        barCheckBox.setText("Bares");
        barCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barCheckBoxActionPerformed(evt);
            }
        });

        cafeCheckBox.setBackground(new java.awt.Color(255, 255, 255));
        cafeCheckBox.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        cafeCheckBox.setText("Cafés");
        cafeCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cafeCheckBoxActionPerformed(evt);
            }
        });

        evCheckBox.setBackground(new java.awt.Color(255, 255, 255));
        evCheckBox.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        evCheckBox.setText("Eventos ");
        evCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                evCheckBoxActionPerformed(evt);
            }
        });

        cultCheckBox.setBackground(new java.awt.Color(255, 255, 255));
        cultCheckBox.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        cultCheckBox.setText("Culturais");
        cultCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cultCheckBoxActionPerformed(evt);
            }
        });

        outrosCheckBox.setBackground(new java.awt.Color(255, 255, 255));
        outrosCheckBox.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        outrosCheckBox.setText("Outros");
        outrosCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outrosCheckBoxActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel4.setText("Cidade:");

        cidadelabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cidadelabelActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 51, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI Symbol", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 204));
        jLabel1.setText("RUBISCO Roteiros Turísticos");

        jLabel6.setBackground(new java.awt.Color(0, 102, 153));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rubisco.jpg"))); // NOI18N

        orcamentolabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orcamentolabelActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel2.setText("Orçamento R$:");

        solicitar.setBackground(new java.awt.Color(0, 51, 204));
        solicitar.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        solicitar.setForeground(new java.awt.Color(255, 255, 255));
        solicitar.setText("Solicitar Roteiro!");
        solicitar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 204), 2));
        solicitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                solicitarActionPerformed(evt);
            }
        });

        jDesktopPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(restCheckBox, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(hotCheckBox, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(barCheckBox, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(cafeCheckBox, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(evCheckBox, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(cultCheckBox, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(outrosCheckBox, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(cidadelabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(orcamentolabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(solicitar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGap(201, 201, 201)
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(hotCheckBox)
                                    .addComponent(cultCheckBox)
                                    .addComponent(outrosCheckBox))
                                .addGap(50, 50, 50))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(restCheckBox)
                                .addGap(18, 18, 18)))
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cafeCheckBox)
                            .addComponent(barCheckBox)
                            .addComponent(evCheckBox)
                            .addComponent(solicitar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(orcamentolabel, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cidadelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(130, 130, 130))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)))
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(orcamentolabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cidadelabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(barCheckBox)
                    .addComponent(restCheckBox))
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cafeCheckBox)
                    .addComponent(hotCheckBox))
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(evCheckBox)
                    .addComponent(cultCheckBox))
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(solicitar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(outrosCheckBox)))
                .addContainerGap())
        );

        jMenu1.setText("Login");

        mLogin.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        mLogin.setText("Tela de login");
        mLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mLoginActionPerformed(evt);
            }
        });
        jMenu1.add(mLogin);

        mLogin1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        mLogin1.setText("Fazer logout");
        mLogin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mLogin1ActionPerformed(evt);
            }
        });
        jMenu1.add(mLogin1);

        mSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        mSair.setText("Sair");
        mSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mSairActionPerformed(evt);
            }
        });
        jMenu1.add(mSair);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Cadastrar");

        jMenuItem2.setText("Turista");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuItem3.setText("Serviço");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuItem4.setText("Provedor");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Listar");

        jMenuItem1.setText("Serviços");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem1);

        jMenuItem5.setText("Atrativos");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem5);

        jMenuBar1.add(jMenu4);

        jMenu22.setText("Sobre");
        jMenu22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu22ActionPerformed(evt);
            }
        });

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem7.setText("Sobre");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu22.add(jMenuItem7);

        jMenuBar1.add(jMenu22);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mLoginActionPerformed
        // TODO add your handling code here:

        Login telog = new Login(controle, listaUsuario, listaProvedor);
        telog.setVisible(true);


    }//GEN-LAST:event_mLoginActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        if (controle.getprovedor() == 1) {
            CadastroServico cad = new CadastroServico(listaServicos, listaCategorias, listaAtrativos);
            cad.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Você deve fazer login como Provedor para cadastrar um serviço!");
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void mSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mSairActionPerformed
        // TODO add your handling code here:
        salvaSerializado();
        System.exit(0);

    }//GEN-LAST:event_mSairActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        //JOptionPane.showMessageDialog(null,"");
        Sobre tela = new Sobre();

        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed

        CadastroTurista cad = new CadastroTurista(listaUsuario);
        cad.setVisible(true);

// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        CadastroProvedor cad = new CadastroProvedor(listaProvedor);
        cad.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        ListaServico lista = new ListaServico(listaServicos);
        lista.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        ListaAtrativo lista = new ListaAtrativo(listaAtrativos);
        lista.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void restCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_restCheckBoxActionPerformed

    private void hotCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hotCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hotCheckBoxActionPerformed

    private void barCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_barCheckBoxActionPerformed

    private void cafeCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cafeCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cafeCheckBoxActionPerformed

    private void evCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_evCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_evCheckBoxActionPerformed

    private void cultCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cultCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cultCheckBoxActionPerformed

    private void outrosCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outrosCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_outrosCheckBoxActionPerformed

    private void cidadelabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cidadelabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cidadelabelActionPerformed

    private void orcamentolabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orcamentolabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_orcamentolabelActionPerformed

    private void solicitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_solicitarActionPerformed
        // TODO add your handling code here: 
        if (controle.getturista() == 1) {
            float orcamento = 0;
            try {
                orcamento = Float.parseFloat(orcamentolabel.getText());
            } catch (NumberFormatException a) {
                JOptionPane.showMessageDialog(null, "O orçamento não deve possuir letras, vírgulas, ou caracteres especiais!");
            }
            if (cidadelabel.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Cidade Obrigatoria!");
            }
            int contopcoes = 0;
            if (restCheckBox.isSelected()) {
                contopcoes = contopcoes + 1;
            }
            if (barCheckBox.isSelected()) {
                contopcoes = contopcoes + 1;
            }
            if (hotCheckBox.isSelected()) {
                contopcoes = contopcoes + 1;
            }
            if (cafeCheckBox.isSelected()) {
                contopcoes = contopcoes + 1;
            }
            if (cultCheckBox.isSelected()) {
                contopcoes = contopcoes + 1;
            }
            if (evCheckBox.isSelected()) {
                contopcoes = contopcoes + 1;
            }
            if (outrosCheckBox.isSelected()) {
                contopcoes = contopcoes + 1;
            }
            if (contopcoes == 0) {
                JOptionPane.showMessageDialog(null, "Nenhuma categoria selecionada!");
            }

            Roteiro rot = new Roteiro(listaServicos, listaAtrativos, listaCategorias, orcamentolabel, cidadelabel, restCheckBox, barCheckBox, hotCheckBox, cafeCheckBox, cultCheckBox, evCheckBox, outrosCheckBox);
            rot.setVisible(true);

        } else {
            JOptionPane.showMessageDialog(null, "Você deve fazer login como Turista para solicitar um roteiro!");
        }


    }//GEN-LAST:event_solicitarActionPerformed

    private void mLogin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mLogin1ActionPerformed
        // TODO add your handling code here:
        controle.setprovedor(0);
        controle.setturista(0);
        JOptionPane.showMessageDialog(null, "Você realizou logout!");

    }//GEN-LAST:event_mLogin1ActionPerformed

    private void jMenu22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu22ActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_jMenu22ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox barCheckBox;
    private javax.swing.JCheckBox cafeCheckBox;
    private javax.swing.JTextField cidadelabel;
    private javax.swing.JCheckBox cultCheckBox;
    private javax.swing.JCheckBox evCheckBox;
    private javax.swing.JCheckBox hotCheckBox;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu22;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem mLogin;
    private javax.swing.JMenuItem mLogin1;
    private javax.swing.JMenuItem mSair;
    private javax.swing.JTextField orcamentolabel;
    private javax.swing.JCheckBox outrosCheckBox;
    private javax.swing.JCheckBox restCheckBox;
    private javax.swing.JButton solicitar;
    // End of variables declaration//GEN-END:variables

    private void recuperaSerializado() {
        System.out.println("Recupera Serializado\n");
        //deserializa
        try {
            listaUsuario = (ArrayList<Usuario>) ps.deserializarListUsuario("ListUsuario");
            listaProvedor = (ArrayList<Usuario>) ps.deserializarListUsuario("ListProvedor");
            listaServicos = (ArrayList<Servico>) ps.deserializarListServico("ListServico");
            listaAtrativos = (ArrayList<Atrativo>) ps.deserializarListAtrativo("ListAtrativo");
        } catch (Exception ex) {
            System.err.println("Falha ao deserializar! - " + ex.toString());
        }
    }

    private void salvaSerializado() {
        System.out.println("Salva Serializado\n");
        //serializa
        try {
            ps.serializarListUsuarios("ListUsuario", listaUsuario);
            ps.serializarListUsuarios("ListProvedor", listaProvedor);
            ps.serializarListServico("ListServico", listaServicos);
            ps.serializarListAtrativo("ListAtrativo", listaAtrativos);
        } catch (Exception ex) {
            System.err.println("Falha ao serializar! - " + ex.toString());
        }
    }
}
